# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CALL_DETAILS_SCHEMA.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CALL_DETAILS_SCHEMA.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x43\x41LL_DETAILS_SCHEMA.proto\".\n\x08\x43\x44RsList\x12\"\n\x0c\x65ventRecords\x18\x01 \x03(\x0b\x32\x0c.EventRecord\"F\n\x0b\x45ventRecord\x12-\n\x10\x63\x61llDetailRecord\x18\x01 \x01(\x0b\x32\x11.CallDetailRecordH\x00\x42\x08\n\x06record\"\x95\x03\n\x10\x43\x61llDetailRecord\x12\x30\n\nrecordType\x18\x01 \x01(\x0e\x32\x1c.CallDetailRecord.RecordType\x12\x10\n\x08recordID\x18\x02 \x01(\x03\x12\x1a\n\x12\x63\x61llingPartyNumber\x18\x03 \x01(\t\x12\x19\n\x11\x63\x61lledPartyNumber\x18\x04 \x01(\t\x12\x15\n\rcallStartTime\x18\x05 \x01(\t\x12\x13\n\x0b\x63\x61llEndTime\x18\x06 \x01(\t\x12\x14\n\x0c\x63\x61llDuration\x18\x07 \x01(\x05\x12,\n\x08\x63\x61llType\x18\x08 \x01(\x0e\x32\x1a.CallDetailRecord.CallType\x12\x11\n\tisRoaming\x18\t \x01(\x08\x12\r\n\x05mscID\x18\n \x01(\t\x12*\n\x13locationInformation\x18\x0b \x01(\x0b\x32\r.LocationInfo\" \n\nRecordType\x12\t\n\x05VOICE\x10\x00\x12\x07\n\x03SMS\x10\x01\"&\n\x08\x43\x61llType\x12\x0c\n\x08INCOMING\x10\x00\x12\x0c\n\x08OUTGOING\x10\x01\"R\n\x0cLocationInfo\x12\x0e\n\x06\x63\x65llID\x18\x01 \x01(\x05\x12\x18\n\x10locationAreaCode\x18\x02 \x01(\x05\x12\x0b\n\x03mcc\x18\x03 \x01(\x05\x12\x0b\n\x03mnc\x18\x04 \x01(\x05\x62\x06proto3')
)



_CALLDETAILRECORD_RECORDTYPE = _descriptor.EnumDescriptor(
  name='RecordType',
  full_name='CallDetailRecord.RecordType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VOICE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SMS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=483,
  serialized_end=515,
)
_sym_db.RegisterEnumDescriptor(_CALLDETAILRECORD_RECORDTYPE)

_CALLDETAILRECORD_CALLTYPE = _descriptor.EnumDescriptor(
  name='CallType',
  full_name='CallDetailRecord.CallType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INCOMING', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTGOING', index=20, number=20,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=517,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_CALLDETAILRECORD_CALLTYPE)


_CDRSLIST = _descriptor.Descriptor(
  name='CDRsList',
  full_name='CDRsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eventRecords', full_name='CDRsList.eventRecords', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=75,
)


_EVENTRECORD = _descriptor.Descriptor(
  name='EventRecord',
  full_name='EventRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='callDetailRecord', full_name='EventRecord.callDetailRecord', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='record', full_name='EventRecord.record',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=77,
  serialized_end=147,
)


_CALLDETAILRECORD = _descriptor.Descriptor(
  name='CallDetailRecord',
  full_name='CallDetailRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recordType', full_name='CallDetailRecord.recordType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recordID', full_name='CallDetailRecord.recordID', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callingPartyNumber', full_name='CallDetailRecord.callingPartyNumber', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calledPartyNumber', full_name='CallDetailRecord.calledPartyNumber', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callStartTime', full_name='CallDetailRecord.callStartTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callEndTime', full_name='CallDetailRecord.callEndTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callDuration', full_name='CallDetailRecord.callDuration', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callType', full_name='CallDetailRecord.callType', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isRoaming', full_name='CallDetailRecord.isRoaming', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mscID', full_name='CallDetailRecord.mscID', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locationInformation', full_name='CallDetailRecord.locationInformation', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CALLDETAILRECORD_RECORDTYPE,
    _CALLDETAILRECORD_CALLTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=555,
)


_LOCATIONINFO = _descriptor.Descriptor(
  name='LocationInfo',
  full_name='LocationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cellID', full_name='LocationInfo.cellID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locationAreaCode', full_name='LocationInfo.locationAreaCode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mcc', full_name='LocationInfo.mcc', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mnc', full_name='LocationInfo.mnc', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=639,
)

_CDRSLIST.fields_by_name['eventRecords'].message_type = _EVENTRECORD
_EVENTRECORD.fields_by_name['callDetailRecord'].message_type = _CALLDETAILRECORD
_EVENTRECORD.oneofs_by_name['record'].fields.append(
  _EVENTRECORD.fields_by_name['callDetailRecord'])
_EVENTRECORD.fields_by_name['callDetailRecord'].containing_oneof = _EVENTRECORD.oneofs_by_name['record']
_CALLDETAILRECORD.fields_by_name['recordType'].enum_type = _CALLDETAILRECORD_RECORDTYPE
_CALLDETAILRECORD.fields_by_name['callType'].enum_type = _CALLDETAILRECORD_CALLTYPE
_CALLDETAILRECORD.fields_by_name['locationInformation'].message_type = _LOCATIONINFO
_CALLDETAILRECORD_RECORDTYPE.containing_type = _CALLDETAILRECORD
_CALLDETAILRECORD_CALLTYPE.containing_type = _CALLDETAILRECORD
DESCRIPTOR.message_types_by_name['CDRsList'] = _CDRSLIST
DESCRIPTOR.message_types_by_name['EventRecord'] = _EVENTRECORD
DESCRIPTOR.message_types_by_name['CallDetailRecord'] = _CALLDETAILRECORD
DESCRIPTOR.message_types_by_name['LocationInfo'] = _LOCATIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CDRsList = _reflection.GeneratedProtocolMessageType('CDRsList', (_message.Message,), dict(
  DESCRIPTOR = _CDRSLIST,
  __module__ = 'CALL_DETAILS_SCHEMA_pb2'
  # @@protoc_insertion_point(class_scope:CDRsList)
  ))
_sym_db.RegisterMessage(CDRsList)

EventRecord = _reflection.GeneratedProtocolMessageType('EventRecord', (_message.Message,), dict(
  DESCRIPTOR = _EVENTRECORD,
  __module__ = 'CALL_DETAILS_SCHEMA_pb2'
  # @@protoc_insertion_point(class_scope:EventRecord)
  ))
_sym_db.RegisterMessage(EventRecord)

CallDetailRecord = _reflection.GeneratedProtocolMessageType('CallDetailRecord', (_message.Message,), dict(
  DESCRIPTOR = _CALLDETAILRECORD,
  __module__ = 'CALL_DETAILS_SCHEMA_pb2'
  # @@protoc_insertion_point(class_scope:CallDetailRecord)
  ))
_sym_db.RegisterMessage(CallDetailRecord)

LocationInfo = _reflection.GeneratedProtocolMessageType('LocationInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONINFO,
  __module__ = 'CALL_DETAILS_SCHEMA_pb2'
  # @@protoc_insertion_point(class_scope:LocationInfo)
  ))
_sym_db.RegisterMessage(LocationInfo)


# @@protoc_insertion_point(module_scope)
